//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public double ID { get; set; }
        public Nullable<double> SalesRep { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
        public string Speaker1 { get; set; }
        public string Speaker2 { get; set; }
        public string Speaker3 { get; set; }
        public string Location1 { get; set; }
        public string Location2 { get; set; }
        public string Location3 { get; set; }
        public string Approved { get; set; }
        public string ApprovedBy { get; set; }
        public string ConfirmedSpeaker { get; set; }
        public string ConfirmedLocation { get; set; }
        public string Name { get; set; }
        public Nullable<double> invitemax { get; set; }
        public Nullable<double> attendeemax { get; set; }
        public string region { get; set; }
        public Nullable<double> ConfirmedLocationId { get; set; }
        public Nullable<double> RequestedLocationId { get; set; }
        public string Product { get; set; }
        public string MeetingType { get; set; }
        public Nullable<double> ConfirmedSpeakerID { get; set; }
        public Nullable<double> ProductId { get; set; }
        public Nullable<double> TopicId { get; set; }
        public string Webinar { get; set; }
        public Nullable<double> ConfirmedAttendees { get; set; }
        public Nullable<double> FoodBevCost { get; set; }
        public Nullable<double> OrigEstCost { get; set; }
        public string AssignedTo { get; set; }
        public Nullable<double> Locked { get; set; }
        public string RTSpeaker2 { get; set; }
        public string RTSpeaker2ID { get; set; }
        public string RequestedFromIpad { get; set; }
    }
}
